spring:
  application:
    name: integration-via-cep-api

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  addresses:
    ws-via-cep: https://viacep.com.br/ws